#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

#expand specific roundcube template
for my $event (qw(
    bootstrap-console-save
    conf-roundcube
    roundcube-update
    console-save
    ))
{
    templates2events("/usr/share/roundcubemail/plugins/managesieve/config.inc.php", $event);
    templates2events("/usr/share/roundcubemail/plugins/sieverules/config.inc.php", $event);
    templates2events("/etc/roundcubemail/config.inc.php", $event);
    templates2events("/etc/e-smith/sql/init/80roundcube", $event);
}

#restart specific services to avoid to reboot after the installation
for  my $event (qw(
    conf-roundcube
    roundcube-update
    ))
{
    templates2events("/etc/httpd/conf/httpd.conf", $event);
    templates2events("/etc/dovecot/dovecot.conf", $event);
    safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/mysql.init");
    safe_symlink("sigusr1", "root/etc/e-smith/events/$event/services2adjust/httpd-e-smith");
    safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/dovecot");
    safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/qmail");
}


#We want to expand /etc/e-smith/templates-user/.qmail
foreach my $event (qw(
    conf-roundcube
    roundcube-update
   ))
{
    event_link("qmail-update-user", $event, "20");
}
safe_symlink("/usr/share/php/Net/LDAP3","root/usr/share/pear/Net/LDAP3");
safe_symlink("/usr/share/php/Net/LDAP3.php","root/usr/share/pear/Net/LDAP3.php");
